#! /usr/bin/env bash


# Reference: https://github.com/so-fancy/diff-so-fancy

if ! [ -x "$(command -v diff-so-fancy)" ]; then
  echo 'Error: diff-so-fancy is not installed. Please Install: https://github.com/so-fancy/diff-so-fancy' >&2
  exit 1
fi

git config --global core.editor "nvim"

git config --global core.pager "diff-so-fancy | less -F -S -R -i -+X"
git config --global interactive.diffFilter "diff-so-fancy --patch"

git config --global color.ui true

git config --global color.diff-highlight.oldNormal    "red bold"
git config --global color.diff-highlight.oldHighlight "red bold 52"
git config --global color.diff-highlight.newNormal    "green bold"
git config --global color.diff-highlight.newHighlight "green bold 22"

git config --global color.diff.meta       "11"
git config --global color.diff.frag       "magenta bold"
git config --global color.diff.func       "146 bold"
git config --global color.diff.commit     "yellow bold"
git config --global color.diff.old        "red bold"
git config --global color.diff.new        "green bold"
git config --global color.diff.whitespace "red reverse"


git config --bool --global diff-so-fancy.markEmptyLines true

git config --bool --global diff-so-fancy.changeHunkIndicators true

git config --bool --global diff-so-fancy.stripLeadingSymbols true
